const services=[
{id:1,name:'Hair Styling',category:'hair',duration:'45 min',price:3500,image:'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=1000&q=85',desc:'Tailored cuts, blow-dries and finishing for an effortless signature look.'},
{id:2,name:'Hair Coloring',category:'hair',duration:'120 min',price:12000,image:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85',desc:'Dimensional colour, gloss and carefully considered tones selected for you.'},
{id:3,name:'Bridal Makeup',category:'bridal',duration:'150 min',price:18000,image:'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1000&q=85',desc:'Refined bridal makeup designed to photograph beautifully and last all day.'},
{id:4,name:'Facial & Skin Care',category:'skin',duration:'60 min',price:6500,image:'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1000&q=85',desc:'Restorative skin rituals using professional techniques and premium products.'},
{id:5,name:'Manicure & Pedicure',category:'nails',duration:'75 min',price:5500,image:'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1000&q=85',desc:'Precise nail care with a polished finish, from classic neutrals to modern colour.'},
{id:6,name:'Spa & Relaxation',category:'spa',duration:'90 min',price:9000,image:'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1000&q=85',desc:'A quiet reset with calming body rituals and an unhurried salon experience.'}
];
function renderServices(target,filter='all'){const el=document.querySelector(target);if(!el)return;const list=filter==='all'?services:services.filter(s=>s.category===filter);el.innerHTML=list.map(s=>`<div class="col-md-6 col-xl-4"><article class="service-card reveal"><div class="service-img"><img src="${s.image}" alt="${s.name}" loading="lazy"></div><div class="service-body"><span class="eyebrow">${s.category}</span><h3 class="serif fs-2 mt-2 mb-2">${s.name}</h3><p class="text-muted-custom small">${s.desc}</p><div class="service-meta"><span>${s.duration}</span><strong>From LKR ${s.price.toLocaleString()}</strong></div><a class="link-arrow d-inline-block mt-4" href="service-details.html?id=${s.id}">View service</a></div></article></div>`).join('');el.querySelectorAll('.reveal').forEach(x=>setTimeout(()=>x.classList.add('visible'),30))}
document.addEventListener('DOMContentLoaded',()=>{renderServices('#servicesGrid');document.querySelectorAll('.filter-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderServices('#servicesGrid',b.dataset.filter)}));const detail=document.querySelector('#serviceDetail');if(detail){const id=new URLSearchParams(location.search).get('id')||'1';const s=services.find(x=>x.id==id)||services[0];detail.innerHTML=`<div class="row g-5 align-items-center"><div class="col-lg-6"><img src="${s.image}" alt="${s.name}" class="w-100" style="height:650px;object-fit:cover"></div><div class="col-lg-5"><span class="eyebrow">${s.category}</span><h1 class="section-title mt-3">${s.name}</h1><p class="text-muted-custom mt-4">${s.desc} Our specialists begin with a short consultation, then tailor every detail to your hair, skin tone, style and occasion.</p><div class="row g-3 my-4"><div class="col-6"><div class="summary-box"><small class="text-muted-custom">Duration</small><div class="serif fs-3">${s.duration}</div></div></div><div class="col-6"><div class="summary-box"><small class="text-muted-custom">Starting from</small><div class="serif fs-3">LKR ${s.price.toLocaleString()}</div></div></div></div><h3 class="serif fs-2">What's included</h3><ul class="ps-3 text-muted-custom small"><li>Personal consultation</li><li>Professional preparation and finishing</li><li>Aftercare recommendations</li><li>Premium salon products</li></ul><a href="booking.html?service=${s.id}" class="btn btn-luxe mt-3">Book this service</a></div></div>`}});
